### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by umerzafar2003** [anam-hossain/html2pdf-converter#37]
i downloaded both 32 and 64 bit files for linux but it failed to run
32 bit file isssue
/bin/phantomjs: cannot execute binary file: /usr/local/cpanel/cgi-sys/ea-php56

64 bit file issue
/bin/phantomjs: ib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory: /usr/local/cpanel/cgi-sys/ea-php56

**Comment by anam-hossain** [comment]
@umerzafar2003 I believe this is a permission issue on your server side. The file is not executable from command line. Please check the Cpanel permission.

**Comment by umerzafar2003** [comment]
successfully generated png and pdf 
i installed phantomjs using below link 
http://smallbigcrazyblog.blogspot.com
